export const DEFAULT_PHASE_DURATION_SECONDS = 300

export const MIN_PHASE_DURATION_SECONDS = 30

export const MAX_PHASE_DURATION_SECONDS = 7200

export const MAX_PROGRAM_NAME_LENGTH = 80

export const MAX_PHASE_NAME_LENGTH = 80

